# 1PB Cloud WebDAV Configuration
address: 127.0.0.1
port: 80
auth: false
scope: C:\vault

# Server Settings
tls: false
modify: true
allow_links: true

# Mapping for E: Drive
# This tells the server to treat C:\vault as the root of the E: Drive